onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /synthi_top_tb/DUT/path_control_1/sw_sync_i
add wave -noupdate /synthi_top_tb/DUT/path_control_1/dds_l_i
add wave -noupdate /synthi_top_tb/DUT/path_control_1/dds_r_i
add wave -noupdate -radix hexadecimal -childformat {{/synthi_top_tb/DUT/path_control_1/adcdat_pl_i(15) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pl_i(14) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pl_i(13) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pl_i(12) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pl_i(11) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pl_i(10) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pl_i(9) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pl_i(8) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pl_i(7) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pl_i(6) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pl_i(5) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pl_i(4) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pl_i(3) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pl_i(2) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pl_i(1) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pl_i(0) -radix hexadecimal}} -expand -subitemconfig {/synthi_top_tb/DUT/path_control_1/adcdat_pl_i(15) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pl_i(14) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pl_i(13) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pl_i(12) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pl_i(11) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pl_i(10) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pl_i(9) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pl_i(8) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pl_i(7) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pl_i(6) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pl_i(5) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pl_i(4) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pl_i(3) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pl_i(2) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pl_i(1) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pl_i(0) {-radix hexadecimal}} /synthi_top_tb/DUT/path_control_1/adcdat_pl_i
add wave -noupdate -radix hexadecimal -childformat {{/synthi_top_tb/DUT/path_control_1/adcdat_pr_i(15) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pr_i(14) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pr_i(13) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pr_i(12) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pr_i(11) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pr_i(10) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pr_i(9) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pr_i(8) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pr_i(7) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pr_i(6) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pr_i(5) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pr_i(4) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pr_i(3) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pr_i(2) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pr_i(1) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/adcdat_pr_i(0) -radix hexadecimal}} -expand -subitemconfig {/synthi_top_tb/DUT/path_control_1/adcdat_pr_i(15) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pr_i(14) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pr_i(13) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pr_i(12) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pr_i(11) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pr_i(10) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pr_i(9) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pr_i(8) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pr_i(7) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pr_i(6) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pr_i(5) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pr_i(4) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pr_i(3) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pr_i(2) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pr_i(1) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/adcdat_pr_i(0) {-radix hexadecimal}} /synthi_top_tb/DUT/path_control_1/adcdat_pr_i
add wave -noupdate -radix hexadecimal -childformat {{/synthi_top_tb/DUT/path_control_1/dacdat_pl_o(15) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/dacdat_pl_o(14) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/dacdat_pl_o(13) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/dacdat_pl_o(12) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/dacdat_pl_o(11) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/dacdat_pl_o(10) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/dacdat_pl_o(9) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/dacdat_pl_o(8) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/dacdat_pl_o(7) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/dacdat_pl_o(6) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/dacdat_pl_o(5) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/dacdat_pl_o(4) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/dacdat_pl_o(3) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/dacdat_pl_o(2) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/dacdat_pl_o(1) -radix hexadecimal} {/synthi_top_tb/DUT/path_control_1/dacdat_pl_o(0) -radix hexadecimal}} -expand -subitemconfig {/synthi_top_tb/DUT/path_control_1/dacdat_pl_o(15) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/dacdat_pl_o(14) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/dacdat_pl_o(13) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/dacdat_pl_o(12) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/dacdat_pl_o(11) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/dacdat_pl_o(10) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/dacdat_pl_o(9) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/dacdat_pl_o(8) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/dacdat_pl_o(7) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/dacdat_pl_o(6) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/dacdat_pl_o(5) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/dacdat_pl_o(4) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/dacdat_pl_o(3) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/dacdat_pl_o(2) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/dacdat_pl_o(1) {-radix hexadecimal} /synthi_top_tb/DUT/path_control_1/dacdat_pl_o(0) {-radix hexadecimal}} /synthi_top_tb/DUT/path_control_1/dacdat_pl_o
add wave -noupdate -radix hexadecimal /synthi_top_tb/DUT/path_control_1/dacdat_pr_o
add wave -noupdate /synthi_top_tb/DUT/path_control_1/sw_sync_i
add wave -noupdate /synthi_top_tb/DUT/path_control_1/sw_sync_i(3)
add wave -noupdate -radix hexadecimal /synthi_top_tb/dacdat_check
add wave -noupdate -divider ja
add wave -noupdate -expand -subitemconfig {/synthi_top_tb/tv_s.obs_data -expand} /synthi_top_tb/tv_s
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {95230 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 411
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {5911314 ns} {6205458 ns}
